// This file is auto-generated by scripts/sync-tokens.mjs.
// Do not edit it manually. Update design/handoff/current/tokens.json and themes.json instead.

export const themeNames = [
  "default",
  "default-dark",
  "harvest",
  "harvest-dark",
  "retro",
  "retro-dark"
] as const;

export type ThemeName = (typeof themeNames)[number];

export const themeFamilyNames = [
  "default",
  "harvest",
  "retro"
] as const;

export type ThemeFamilyName =
  | "default"
  | "harvest"
  | "retro";

export const themeModes = [
  "light",
  "dark"
] as const;

export type ThemeMode =
  | "light"
  | "dark";

export const themeCatalog = {
  "default": {
    "label": "Default",
    "family": "Default",
    "familyKey": "default",
    "mode": "light",
    "familyName": "default"
  },
  "default-dark": {
    "label": "Default Dark",
    "family": "Default",
    "familyKey": "default",
    "mode": "dark",
    "familyName": "default"
  },
  "harvest": {
    "label": "Harvest",
    "family": "Harvest",
    "familyKey": "harvest",
    "mode": "light",
    "familyName": "harvest"
  },
  "harvest-dark": {
    "label": "Harvest Dark",
    "family": "Harvest",
    "familyKey": "harvest",
    "mode": "dark",
    "familyName": "harvest"
  },
  "retro": {
    "label": "Retro",
    "family": "Retro",
    "familyKey": "retro",
    "mode": "light",
    "familyName": "retro"
  },
  "retro-dark": {
    "label": "Retro Dark",
    "family": "Retro",
    "familyKey": "retro",
    "mode": "dark",
    "familyName": "retro"
  }
} as const;

export const themeFamilyCatalog = {
  "default": {
    "label": "Default",
    "themes": {
      "light": "default",
      "dark": "default-dark"
    }
  },
  "harvest": {
    "label": "Harvest",
    "themes": {
      "light": "harvest",
      "dark": "harvest-dark"
    }
  },
  "retro": {
    "label": "Retro",
    "themes": {
      "light": "retro",
      "dark": "retro-dark"
    }
  }
} as const;

export type ColorTokenName =
  | "background"
  | "foreground"
  | "card"
  | "cardForeground"
  | "popover"
  | "popoverForeground"
  | "secondary"
  | "secondaryForeground"
  | "muted"
  | "mutedForeground"
  | "accent"
  | "accentForeground"
  | "border"
  | "input"
  | "ring"
  | "primary"
  | "primaryForeground"
  | "primarySoft"
  | "primarySoftForeground"
  | "destructive"
  | "destructiveForeground"
  | "success"
  | "successForeground"
  | "brand"
  | "overlay";

export type RadiusTokenName =
  | "xs"
  | "sm"
  | "md"
  | "lg"
  | "xl"
  | "full";

type ThemeScale<T> = Record<ThemeName, T>;

type DesignTokens = {
  colors: Record<ColorTokenName, ThemeScale<string>>;
  radius: Record<RadiusTokenName, ThemeScale<string>>;
};

export const designTokens = {
  "colors": {
    "background": {
      "default": "#ffffff",
      "default-dark": "#0f172a",
      "harvest": "#ffffff",
      "harvest-dark": "#0f172a",
      "retro": "#ffffff",
      "retro-dark": "#0f172a"
    },
    "foreground": {
      "default": "#1f2937",
      "default-dark": "#e5e7eb",
      "harvest": "#1f2937",
      "harvest-dark": "#e5e7eb",
      "retro": "#1f2937",
      "retro-dark": "#e5e7eb"
    },
    "card": {
      "default": "#ffffff",
      "default-dark": "#1e293b",
      "harvest": "#ffffff",
      "harvest-dark": "#1e293b",
      "retro": "#ffffff",
      "retro-dark": "#1e293b"
    },
    "cardForeground": {
      "default": "#1f2937",
      "default-dark": "#e5e7eb",
      "harvest": "#1f2937",
      "harvest-dark": "#e5e7eb",
      "retro": "#1f2937",
      "retro-dark": "#e5e7eb"
    },
    "popover": {
      "default": "#ffffff",
      "default-dark": "#1e293b",
      "harvest": "#ffffff",
      "harvest-dark": "#1e293b",
      "retro": "#ffffff",
      "retro-dark": "#1e293b"
    },
    "popoverForeground": {
      "default": "#1f2937",
      "default-dark": "#e5e7eb",
      "harvest": "#1f2937",
      "harvest-dark": "#e5e7eb",
      "retro": "#1f2937",
      "retro-dark": "#e5e7eb"
    },
    "secondary": {
      "default": "#f8fafc",
      "default-dark": "#1e293b",
      "harvest": "#f8fafc",
      "harvest-dark": "#1e293b",
      "retro": "#f8fafc",
      "retro-dark": "#1e293b"
    },
    "secondaryForeground": {
      "default": "#1f2937",
      "default-dark": "#e5e7eb",
      "harvest": "#1f2937",
      "harvest-dark": "#e5e7eb",
      "retro": "#1f2937",
      "retro-dark": "#e5e7eb"
    },
    "muted": {
      "default": "#f8fafc",
      "default-dark": "#1e293b",
      "harvest": "#f8fafc",
      "harvest-dark": "#1e293b",
      "retro": "#f8fafc",
      "retro-dark": "#1e293b"
    },
    "mutedForeground": {
      "default": "#6b7280",
      "default-dark": "#9ca3af",
      "harvest": "#6b7280",
      "harvest-dark": "#9ca3af",
      "retro": "#6b7280",
      "retro-dark": "#9ca3af"
    },
    "accent": {
      "default": "#dbeafe",
      "default-dark": "#3b82f633",
      "harvest": "#fef3c7",
      "harvest-dark": "#f59e0b33",
      "retro": "#fae8ff",
      "retro-dark": "#d946ef33"
    },
    "accentForeground": {
      "default": "#1e40af",
      "default-dark": "#60a5fa",
      "harvest": "#92400e",
      "harvest-dark": "#fbbf24",
      "retro": "#86198f",
      "retro-dark": "#e879f9"
    },
    "border": {
      "default": "#e5e7eb",
      "default-dark": "#374151",
      "harvest": "#e5e7eb",
      "harvest-dark": "#374151",
      "retro": "#e5e7eb",
      "retro-dark": "#374151"
    },
    "input": {
      "default": "#e5e7eb",
      "default-dark": "#374151",
      "harvest": "#e5e7eb",
      "harvest-dark": "#374151",
      "retro": "#e5e7eb",
      "retro-dark": "#374151"
    },
    "ring": {
      "default": "#2563eb",
      "default-dark": "#3b82f6",
      "harvest": "#f59e0b",
      "harvest-dark": "#f59e0b",
      "retro": "#d946ef",
      "retro-dark": "#d946ef"
    },
    "primary": {
      "default": "#1e40af",
      "default-dark": "#60a5fa",
      "harvest": "#92400e",
      "harvest-dark": "#fbbf24",
      "retro": "#86198f",
      "retro-dark": "#e879f9"
    },
    "primaryForeground": {
      "default": "#ffffff",
      "default-dark": "#0f172a",
      "harvest": "#ffffff",
      "harvest-dark": "#1f2937",
      "retro": "#ffffff",
      "retro-dark": "#0f172a"
    },
    "primarySoft": {
      "default": "#eff6ff",
      "default-dark": "#3b82f61a",
      "harvest": "#fffbeb",
      "harvest-dark": "#f59e0b1a",
      "retro": "#fdf4ff",
      "retro-dark": "#d946ef1a"
    },
    "primarySoftForeground": {
      "default": "#1e40af",
      "default-dark": "#60a5fa",
      "harvest": "#92400e",
      "harvest-dark": "#fbbf24",
      "retro": "#86198f",
      "retro-dark": "#e879f9"
    },
    "destructive": {
      "default": "#ef4444",
      "default-dark": "#ef4444",
      "harvest": "#ef4444",
      "harvest-dark": "#ef4444",
      "retro": "#ef4444",
      "retro-dark": "#ef4444"
    },
    "destructiveForeground": {
      "default": "#ffffff",
      "default-dark": "#ffffff",
      "harvest": "#ffffff",
      "harvest-dark": "#ffffff",
      "retro": "#ffffff",
      "retro-dark": "#ffffff"
    },
    "success": {
      "default": "#14b8a6",
      "default-dark": "#14b8a6",
      "harvest": "#14b8a6",
      "harvest-dark": "#14b8a6",
      "retro": "#14b8a6",
      "retro-dark": "#14b8a6"
    },
    "successForeground": {
      "default": "#ffffff",
      "default-dark": "#042f2e",
      "harvest": "#ffffff",
      "harvest-dark": "#042f2e",
      "retro": "#ffffff",
      "retro-dark": "#042f2e"
    },
    "brand": {
      "default": "#2563eb",
      "default-dark": "#3b82f6",
      "harvest": "#f59e0b",
      "harvest-dark": "#f59e0b",
      "retro": "#d946ef",
      "retro-dark": "#d946ef"
    },
    "overlay": {
      "default": "#9ca3af",
      "default-dark": "#374151",
      "harvest": "#9ca3af",
      "harvest-dark": "#374151",
      "retro": "#9ca3af",
      "retro-dark": "#374151"
    }
  },
  "radius": {
    "xs": {
      "default": "2px",
      "default-dark": "2px",
      "harvest": "2px",
      "harvest-dark": "2px",
      "retro": "0px",
      "retro-dark": "0px"
    },
    "sm": {
      "default": "4px",
      "default-dark": "4px",
      "harvest": "4px",
      "harvest-dark": "4px",
      "retro": "0px",
      "retro-dark": "0px"
    },
    "md": {
      "default": "6px",
      "default-dark": "6px",
      "harvest": "6px",
      "harvest-dark": "6px",
      "retro": "0px",
      "retro-dark": "0px"
    },
    "lg": {
      "default": "8px",
      "default-dark": "8px",
      "harvest": "8px",
      "harvest-dark": "8px",
      "retro": "0px",
      "retro-dark": "0px"
    },
    "xl": {
      "default": "12px",
      "default-dark": "12px",
      "harvest": "12px",
      "harvest-dark": "12px",
      "retro": "0px",
      "retro-dark": "0px"
    },
    "full": {
      "default": "999px",
      "default-dark": "999px",
      "harvest": "999px",
      "harvest-dark": "999px",
      "retro": "0px",
      "retro-dark": "0px"
    }
  }
} as const satisfies DesignTokens;

export type ThemeColorTokens = {
  [K in keyof typeof designTokens.colors]: (typeof designTokens.colors)[K][ThemeName];
};

export type ThemeRadiusTokens = {
  [K in keyof typeof designTokens.radius]: (typeof designTokens.radius)[K][ThemeName];
};

export function resolveThemeName(themeFamily: ThemeFamilyName, mode: ThemeMode = "light") {
  const family = themeFamilyCatalog[themeFamily];

  return (family.themes[mode] ?? family.themes.light) as ThemeName;
}

export function parseThemeName(theme: ThemeName) {
  const descriptor = themeCatalog[theme];

  return {
    family: descriptor.family,
    familyName: descriptor.familyName as ThemeFamilyName,
    label: descriptor.label,
    mode: descriptor.mode as ThemeMode
  };
}

export function getThemeTokens(theme: ThemeName) {
  const colors = Object.fromEntries(
    Object.entries(designTokens.colors).map(([tokenName, values]) => [tokenName, values[theme]])
  ) as ThemeColorTokens;

  const radius = Object.fromEntries(
    Object.entries(designTokens.radius).map(([tokenName, values]) => [tokenName, values[theme]])
  ) as ThemeRadiusTokens;

  return {
    colors,
    radius
  };
}
