import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(__dirname, "..");
const workspaceRoot = path.resolve(packageRoot, "..", "..");
const designRoot = path.join(workspaceRoot, "design");
const handoffRoot = path.join(designRoot, "handoff", "current");
const tokensSourcePath = path.join(handoffRoot, "tokens.json");
const themesSourcePath = path.join(handoffRoot, "themes.json");
const sourcePath = path.join(packageRoot, "src", "token-source.json");
const tokensPath = path.join(packageRoot, "src", "tokens.ts");
const themeCssPath = path.join(packageRoot, "theme.css");

const tokenSource = JSON.parse(await readFile(tokensSourcePath, "utf8"));
const themesSource = JSON.parse(await readFile(themesSourcePath, "utf8"));

const source = {
  fontSans: tokenSource.fontSans,
  themes: themesSource.themes,
  colors: tokenSource.colors,
  radius: tokenSource.radius
};

const themeEntries = Object.entries(source.themes);
const themeNames = themeEntries.map(([themeName]) => themeName);
const colorTokenNames = Object.keys(source.colors);
const radiusTokenNames = Object.keys(source.radius);
const themeModes = [...new Set(themeEntries.map(([, theme]) => theme.mode))];

const themeFamilies = [];
const themeFamilyMap = new Map();

for (const [themeName, theme] of themeEntries) {
  if (!themeFamilyMap.has(theme.family)) {
    themeFamilyMap.set(theme.family, {
      familyName: theme.mode === "light" ? themeName : themeName.replace(/-dark$/, ""),
      label: theme.family,
      themes: {}
    });
    themeFamilies.push(theme.family);
  }

  const familyDescriptor = themeFamilyMap.get(theme.family);

  if (theme.mode === "light") {
    familyDescriptor.familyName = themeName;
  }

  familyDescriptor.themes[theme.mode] = themeName;
}

const themeFamilyCatalog = Object.fromEntries(
  [...themeFamilyMap.values()].map((family) => [
    family.familyName,
    {
      label: family.label,
      themes: family.themes
    }
  ])
);

const themeFamilyNames = Object.keys(themeFamilyCatalog);
const themeCatalog = Object.fromEntries(
  themeEntries.map(([themeName, theme]) => [
    themeName,
    {
      ...theme,
      familyName: themeFamilyMap.get(theme.family).familyName
    }
  ])
);

function toKebabCase(value) {
  return value.replace(/[A-Z]/g, (match) => `-${match.toLowerCase()}`);
}

function serialize(value, indent = 2) {
  return JSON.stringify(value, null, indent);
}

function buildTokensTs() {
  const themeUnion = themeNames.map((name) => `  | ${serialize(name)}`).join("\n");
  const themeFamilyUnion = themeFamilyNames.map((name) => `  | ${serialize(name)}`).join("\n");
  const themeModeUnion = themeModes.map((name) => `  | ${serialize(name)}`).join("\n");
  const colorUnion = colorTokenNames.map((name) => `  | ${serialize(name)}`).join("\n");
  const radiusUnion = radiusTokenNames.map((name) => `  | ${serialize(name)}`).join("\n");

  return `// This file is auto-generated by scripts/sync-tokens.mjs.
// Do not edit it manually. Update design/handoff/current/tokens.json and themes.json instead.

export const themeNames = ${serialize(themeNames, 2)} as const;

export type ThemeName = (typeof themeNames)[number];

export const themeFamilyNames = ${serialize(themeFamilyNames, 2)} as const;

export type ThemeFamilyName =
${themeFamilyUnion};

export const themeModes = ${serialize(themeModes, 2)} as const;

export type ThemeMode =
${themeModeUnion};

export const themeCatalog = ${serialize(themeCatalog, 2)} as const;

export const themeFamilyCatalog = ${serialize(themeFamilyCatalog, 2)} as const;

export type ColorTokenName =
${colorUnion};

export type RadiusTokenName =
${radiusUnion};

type ThemeScale<T> = Record<ThemeName, T>;

type DesignTokens = {
  colors: Record<ColorTokenName, ThemeScale<string>>;
  radius: Record<RadiusTokenName, ThemeScale<string>>;
};

export const designTokens = ${serialize(
    {
      colors: source.colors,
      radius: source.radius
    },
    2
  )} as const satisfies DesignTokens;

export type ThemeColorTokens = {
  [K in keyof typeof designTokens.colors]: (typeof designTokens.colors)[K][ThemeName];
};

export type ThemeRadiusTokens = {
  [K in keyof typeof designTokens.radius]: (typeof designTokens.radius)[K][ThemeName];
};

export function resolveThemeName(themeFamily: ThemeFamilyName, mode: ThemeMode = "light") {
  const family = themeFamilyCatalog[themeFamily];

  return (family.themes[mode] ?? family.themes.light) as ThemeName;
}

export function parseThemeName(theme: ThemeName) {
  const descriptor = themeCatalog[theme];

  return {
    family: descriptor.family,
    familyName: descriptor.familyName as ThemeFamilyName,
    label: descriptor.label,
    mode: descriptor.mode as ThemeMode
  };
}

export function getThemeTokens(theme: ThemeName) {
  const colors = Object.fromEntries(
    Object.entries(designTokens.colors).map(([tokenName, values]) => [tokenName, values[theme]])
  ) as ThemeColorTokens;

  const radius = Object.fromEntries(
    Object.entries(designTokens.radius).map(([tokenName, values]) => [tokenName, values[theme]])
  ) as ThemeRadiusTokens;

  return {
    colors,
    radius
  };
}
`;
}

function buildThemeCss() {
  const buildThemeBlock = (selector, themeName, { includeFontSans = false, includeColorScheme = false } = {}) => {
    const lines = [];

    if (includeColorScheme || source.themes[themeName].mode === "dark") {
      lines.push("  color-scheme: dark;");
    }

    if (includeFontSans) {
      lines.push(`  --cc-font-sans: ${source.fontSans};`);
    }

    for (const tokenName of colorTokenNames) {
      lines.push(`  --cc-${toKebabCase(tokenName)}: ${source.colors[tokenName][themeName]};`);
    }

    for (const tokenName of radiusTokenNames) {
      lines.push(`  --cc-radius-${toKebabCase(tokenName)}: ${source.radius[tokenName][themeName]};`);
    }

    return `${selector} {\n${lines.join("\n")}\n}`;
  };

  const lightBlocks = themeFamilyNames.map((themeFamily, index) => {
    const selector =
      themeFamily === "default"
        ? `:root,\n[data-theme=${serialize(themeFamily)}]`
        : `[data-theme=${serialize(themeFamily)}]`;
    const themeName = themeFamilyCatalog[themeFamily].themes.light;

    return buildThemeBlock(selector, themeName, {
      includeFontSans: index === 0
    });
  });

  const darkBlocks = themeFamilyNames
    .map((themeFamily) => {
      const themeName = themeFamilyCatalog[themeFamily].themes.dark;

      if (!themeName) return null;

      const selector =
        themeFamily === "default"
          ? `:root[data-mode="dark"],\n:root.dark,\n[data-theme=${serialize(themeFamily)}][data-mode="dark"],\n[data-theme=${serialize(themeFamily)}].dark`
          : `[data-theme=${serialize(themeFamily)}][data-mode="dark"],\n[data-theme=${serialize(themeFamily)}].dark`;

      return buildThemeBlock(selector, themeName, {
        includeColorScheme: true
      });
    })
    .filter(Boolean);

  const themeInlineLines = [
    "  --font-sans: var(--cc-font-sans);",
    ...colorTokenNames.map(
      (tokenName) => `  --color-${toKebabCase(tokenName)}: var(--cc-${toKebabCase(tokenName)});`
    ),
    ...radiusTokenNames.map(
      (tokenName) =>
        `  --radius-${toKebabCase(tokenName)}: var(--cc-radius-${toKebabCase(tokenName)});`
    )
  ];

  return `/* This file is auto-generated by scripts/sync-tokens.mjs. */
${[...lightBlocks, ...darkBlocks].join("\n\n")}

@theme inline {
${themeInlineLines.join("\n")}
}
`;
}

await writeFile(sourcePath, `${serialize(source)}\n`, "utf8");
await writeFile(tokensPath, buildTokensTs(), "utf8");
await writeFile(themeCssPath, buildThemeCss(), "utf8");

console.log(
  `Synced tokens from ${path.relative(workspaceRoot, tokensSourcePath)} and ${path.relative(
    workspaceRoot,
    themesSourcePath
  )}`
);
