import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(__dirname, "..");
const sourcePath = path.join(packageRoot, "src", "token-source.json");
const tokensPath = path.join(packageRoot, "src", "tokens.ts");
const themeCssPath = path.join(packageRoot, "theme.css");

const source = JSON.parse(await readFile(sourcePath, "utf8"));

const themeNames = Object.keys(source.themes);
const colorTokenNames = Object.keys(source.colors);
const radiusTokenNames = Object.keys(source.radius);

function toKebabCase(value) {
  return value.replace(/[A-Z]/g, (match) => `-${match.toLowerCase()}`);
}

function serialize(value, indent = 2) {
  return JSON.stringify(value, null, indent);
}

function buildTokensTs() {
  const themeUnion = themeNames.map((name) => `  | ${serialize(name)}`).join("\n");
  const colorUnion = colorTokenNames.map((name) => `  | ${serialize(name)}`).join("\n");
  const radiusUnion = radiusTokenNames.map((name) => `  | ${serialize(name)}`).join("\n");

  return `// This file is auto-generated by scripts/sync-tokens.mjs.
// Do not edit it manually. Update src/token-source.json instead.

export const themeNames = ${serialize(themeNames, 2)} as const;

export type ThemeName = (typeof themeNames)[number];

export const themeCatalog = ${serialize(source.themes, 2)} as const;

export type ColorTokenName =
${colorUnion};

export type RadiusTokenName =
${radiusUnion};

type ThemeScale<T> = Record<ThemeName, T>;

type DesignTokens = {
  colors: Record<ColorTokenName, ThemeScale<string>>;
  radius: Record<RadiusTokenName, ThemeScale<string>>;
};

export const designTokens = ${serialize(
    {
      colors: source.colors,
      radius: source.radius
    },
    2
  )} as const satisfies DesignTokens;

export type ThemeColorTokens = {
  [K in keyof typeof designTokens.colors]: (typeof designTokens.colors)[K][ThemeName];
};

export type ThemeRadiusTokens = {
  [K in keyof typeof designTokens.radius]: (typeof designTokens.radius)[K][ThemeName];
};

export function getThemeTokens(theme: ThemeName) {
  const colors = Object.fromEntries(
    Object.entries(designTokens.colors).map(([tokenName, values]) => [tokenName, values[theme]])
  ) as ThemeColorTokens;

  const radius = Object.fromEntries(
    Object.entries(designTokens.radius).map(([tokenName, values]) => [tokenName, values[theme]])
  ) as ThemeRadiusTokens;

  return {
    colors,
    radius
  };
}
`;
}

function buildThemeCss() {
  const blocks = themeNames.map((themeName, index) => {
    const selector =
      themeName === "default"
        ? `:root,\n[data-theme=${serialize(themeName)}]`
        : `[data-theme=${serialize(themeName)}]`;
    const lines = [];

    if (source.themes[themeName].mode === "dark") {
      lines.push("  color-scheme: dark;");
    }

    if (index === 0) {
      lines.push(`  --cc-font-sans: ${source.fontSans};`);
    }

    for (const tokenName of colorTokenNames) {
      lines.push(`  --cc-${toKebabCase(tokenName)}: ${source.colors[tokenName][themeName]};`);
    }

    for (const tokenName of radiusTokenNames) {
      lines.push(`  --cc-radius-${toKebabCase(tokenName)}: ${source.radius[tokenName][themeName]};`);
    }

    return `${selector} {\n${lines.join("\n")}\n}`;
  });

  const themeInlineLines = [
    "  --font-sans: var(--cc-font-sans);",
    ...colorTokenNames.map(
      (tokenName) => `  --color-${toKebabCase(tokenName)}: var(--cc-${toKebabCase(tokenName)});`
    ),
    ...radiusTokenNames.map(
      (tokenName) =>
        `  --radius-${toKebabCase(tokenName)}: var(--cc-radius-${toKebabCase(tokenName)});`
    )
  ];

  return `/* This file is auto-generated by scripts/sync-tokens.mjs. */
${blocks.join("\n\n")}

@theme inline {
${themeInlineLines.join("\n")}
}
`;
}

await writeFile(tokensPath, buildTokensTs(), "utf8");
await writeFile(themeCssPath, buildThemeCss(), "utf8");

console.log(`Synced tokens from ${path.relative(packageRoot, sourcePath)}`);
